run:
	time ./target/release/mago-syntax-bench parallel ../laravel

run-single:
	time ./target/release/mago-syntax-bench single ../laravel

dump:
	./target/release/mago-syntax-bench dump ../sample-class.php
